// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── WEB ────────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Eid33PgafpBCZs8tl-PwUhKNLuMBntk',
    authDomain: 'venkat-d22fa.firebaseapp.com',
    projectId: 'venkat-d22fa',
    storageBucket: 'venkat-d22fa.firebasestorage.app',
    messagingSenderId: '871496746385',
    appId: '1:871496746385:web:6031a07a0f2209f73c8630',
  );

  // ── ANDROID ─────────────────────────────────────────────────────────────────
  // Add your google-services.json to android/app/ and replace these values.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbkTnS2hssyCkpz8q2-eSGD3gi8QBDUE8',
    appId: '1:871496746385:android:a77e5c0fc99c157d3c8630',
    messagingSenderId: '871496746385',
    projectId: 'venkat-d22fa',
    storageBucket: 'venkat-d22fa.firebasestorage.app',
  );

  // ── iOS ─────────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Eid33PgafpBCZs8tl-PwUhKNLuMBntk',
    appId: '1:871496746385:ios:6031a07a0f2209f73c8630',
    messagingSenderId: '871496746385',
    projectId: 'venkat-d22fa',
    storageBucket: 'venkat-d22fa.firebasestorage.app',
    iosBundleId: 'com.example.venkat',
  );

  // ── macOS ────────────────────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Eid33PgafpBCZs8tl-PwUhKNLuMBntk',
    appId: '1:871496746385:ios:6031a07a0f2209f73c8630',
    messagingSenderId: '871496746385',
    projectId: 'venkat-d22fa',
    storageBucket: 'venkat-d22fa.firebasestorage.app',
    iosBundleId: 'com.example.venkat',
  );

  // ── WINDOWS ──────────────────────────────────────────────────────────────────
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4Eid33PgafpBCZs8tl-PwUhKNLuMBntk',
    appId: '1:871496746385:web:6031a07a0f2209f73c8630',
    messagingSenderId: '871496746385',
    projectId: 'venkat-d22fa',
    storageBucket: 'venkat-d22fa.firebasestorage.app',
  );
}
